apiVersion: v1
kind: Service
metadata:
  name: recipes-backend
  labels:
    app: recipes-backend
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3031
    targetPort: 3031
  selector:
    app: recipes-backend
