apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: recipes-ingress
spec:
  rules:
  - host: frontend.example.org
    http:
      paths:
      - backend:
          serviceName: recipes-frontend
          servicePort: 80
