apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.storageSize}}
  {{ if (.Values.storage) and eq .Values.storage "digitalocean" }}
  storageClassName: do-block-storage
  {{ end }}
