apiVersion: v1
kind: Service
metadata:
  name: db-recipes
  labels:
    app: db-recipes
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: db-recipes
