apiVersion: v1
kind: Service
metadata:
  name: recipes-frontend
  labels:
    app: recipes-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: recipes-frontend
