apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: recipes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    {{ if .Values.clientCert }}
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-secret: "default/ca-secret"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    {{ end }}
spec:
  tls:
  - hosts:
    - {{.Values.appHost}}
    {{ if .Values.clientCert }}
    secretName: tls-secret
    {{ else }}
    secretName: letsencrypt-production
    {{ end }}
  rules:
  - host: {{.Values.appHost}}
    http:
      paths:
      - path: /
        backend:
          serviceName: recipes-frontend
          servicePort: 80
      - path: /recipes
        backend:
          serviceName: recipes-backend-nginx
          servicePort: 80
      - path: /admin
        backend:
          serviceName: recipes-backend-nginx
          servicePort: 80
      - path: /static
        backend:
          serviceName: recipes-backend-nginx
          servicePort: 80
