apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: recipes-ingress
spec:
  rules:
  - host: {{.Values.frontendHost}}
    http:
      paths:
      - backend:
          serviceName: recipes-frontend
          servicePort: 80
  - host: {{.Values.backendHost}}
    http:
      paths:
      - backend:
          serviceName: recipes-backend-nginx
          servicePort: 80
