apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: recipes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
spec:
  tls:
  - hosts:
    - {{.Values.frontendHost}}
    - {{.Values.backendHost}}
    secretName: letsencrypt-production
  rules:
  - host: {{.Values.frontendHost}}
    http:
      paths:
      - backend:
          serviceName: recipes-frontend
          servicePort: 80
  - host: {{.Values.backendHost}}
    http:
      paths:
      - backend:
          serviceName: recipes-backend-nginx
          servicePort: 80
